"""Added tables

Revision ID: 7cd00f0aa656
Revises: b41bbce04d8a
Create Date: 2024-01-20 20:19:16.932757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd00f0aa656'
down_revision: Union[str, None] = 'b41bbce04d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
